### ISSUE TITLE
Feature Request - `leo jira <TICKET NUMBER/ALIAS>`

### ISSUE THREAD

**Issue by jamesaspence** [theosyslack/leo#1]
`leo jira PROJ-1234`.

This would open up the specified ticket number in the specified JIRA board, i.e. https://jira.site.com/browse/PROJ-1234. We'd need to store a mapping of ticket prefix (`PROJ`) and its root URL (`https://jira.site.com`). If that value was missing we'd presumably need to ask what the root URL was and parse out the root (i.e. if they provide `https://jira.site.com/browse/PROJ-1234` we'd retrieve just `https://jira.site.com`)

It'd be nice to also be able to use aliases for this - i.e. if you had saved a ticket as the title `foo`, you could write `leo jira foo` and it would open the proper link.

**Comment by theosyslack** [comment]
@jamesaspence I've added the first part -- `leo jira PROJ-1234` would copy the link for `PROJ-1234`, if available.

**Comment by jamesaspence** [comment]
perfect, that sounds good!
