### ISSUE TITLE
Alias Support

### ISSUE THREAD

**Issue by theosyslack** [theosyslack/leo#3]
Users should be able to add aliases for their tickets. For instance, a ticket can be referenced by `fixSidebar` and be pulled up with `leo jira fixSidebar`. 

h/t to @jamesaspence (feel free to add any detail, James)

**Comment by jamesaspence** [comment]
Linking to related ticket: https://github.com/theosyslack/leo/issues/1. Basically, a way to quickly reference a ticket by an alias or title - `leo jira foo` will open that ticket link automatically.

**Comment by jamesaspence** [comment]
I got this!
